sources:
  - name: raw_data      # <--- This is the "Nickname"
    database: medical_db
    schema: raw         # <--- This is the real schema in Postgres
    tables:
      - name: telegram_messages # <--- This is the real table name