import os
import pandas as pd
from pathlib import Path
from dotenv import load_dotenv
import psycopg2
from psycopg2.extras import execute_values
from typing import Tuple

# -----------------------------------------------------------------------------
# Load environment variables
# -----------------------------------------------------------------------------
load_dotenv()

# -----------------------------------------------------------------------------
# 1. Database connection setup
# -----------------------------------------------------------------------------
def get_db_connection() -> Tuple[psycopg2.extensions.connection, psycopg2.extensions.cursor]:
    try:
        conn = psycopg2.connect(
            dbname=os.getenv("DATABASE_NAME"),
            user=os.getenv("DATABASE_USER"),
            password=os.getenv("DATABASE_PASSWORD"),
            host=os.getenv("DATABASE_HOST"),
            port=os.getenv("DATABASE_PORT")
        )
        cur = conn.cursor()
        return conn, cur
    except Exception as e:
        print(f"❌ Connection failed: {e}")
        exit()

# -----------------------------------------------------------------------------
# 2. Ensure schema and table exist
# -----------------------------------------------------------------------------
def ensure_schema_and_table(conn, cursor) -> None:
    """Creates the raw schema and the table for YOLO results."""
    cursor.execute("""
    CREATE SCHEMA IF NOT EXISTS raw;

    CREATE TABLE IF NOT EXISTS raw.yolo_detections (
        message_id BIGINT,
        channel TEXT,
        image_name TEXT,
        detected_objects TEXT,
        confidence_score FLOAT,
        image_category TEXT,
        loaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    """)
    conn.commit()

# -----------------------------------------------------------------------------
# 3. Load CSV and insert into database
# -----------------------------------------------------------------------------
def load_csv_to_db(csv_path: Path, cursor: psycopg2.extensions.cursor) -> None:
    """Reads the YOLO CSV, cleans types, and performs a bulk insert."""
    if not csv_path.exists():
        print(f"❌ CSV file not found at {csv_path}")
        return

    # Read CSV
    df = pd.read_csv(csv_path)
    
    # --- CLEANING STEP ---
    # 1. Ensure message_id is only digits (removes '.jpg' or other suffixes)
    # We use regex to extract only the numeric part
    df['message_id'] = df['message_id'].astype(str).str.extract(r'(\d+)').astype(int)    
    # 2. Handle NaN (Not a Number) values in confidence_score
    df['confidence_score'] = df['confidence_score'].fillna(0.0)
    
    # 3. Handle empty detected_objects
    df['detected_objects'] = df['detected_objects'].fillna('none')
    # ---------------------

    # Convert DataFrame to list of tuples
    records = list(df.itertuples(index=False, name=None))

    if records:
        execute_values(
            cursor,
            """
            INSERT INTO raw.yolo_detections 
            (message_id, channel, image_name, detected_objects, confidence_score, image_category)
            VALUES %s
            """,
            records
        )
        print(f"✅ Cleaned and loaded {len(records)} records into raw.yolo_detections")
# -----------------------------------------------------------------------------
# Main Execution
# -----------------------------------------------------------------------------
if __name__ == "__main__":
    conn, cur = get_db_connection()
    ensure_schema_and_table(conn, cur)

    # Define path to the CSV generated by yolo_detect.py
    base_dir = Path(__file__).resolve().parent.parent
    csv_path = base_dir / "data" / "raw" / "yolo_detections.csv"

    load_csv_to_db(csv_path, cur)

    # Cleanup
    conn.commit()
    cur.close()
    conn.close()
    print("🎉 YOLO detection data loaded successfully!")